### ISSUE TITLE
Eval episode count

### ISSUE THREAD

**Issue by Lan131** [niiceMing/CMTA#4]
Your paper mentions 20 eval episodes. Is this controlled via metaworld.yml or the call in CMTA.sh?

**Comment by niiceMing** [comment]
Eval frequency is controlled by ```eval _freq``` in config/experiment/metaworld.yaml.
Here we use ```eval _freq:3000```, which means we eval our agent every 3000 step. And the episode length of metaworld-v1 is 150, which means we do eval every 20 episodes.

**Comment by yyds-xtt** [comment]
Your paper mentions 20 eval episodes. Is this controlled via metaworld.yml or the call in CMTA.sh?

**Comment by yyds-xtt** [comment]
Your paper mentions 20 eval episodes. Is this controlled via metaworld.yml or the call in CMTA.sh?
