### ISSUE TITLE
single SAC baseline critic does not work

### ISSUE THREAD

**Issue by Lan131** [niiceMing/CMTA#5]
File "/home/research/lanier.m/Desktop/CMTA/mtrl/agent/components/critic.py", line 495, in forward
    encoding, next_hidden, ori_encoding = self.encode(mtobs=temp_mtobs, detach=detach_encoder)
ValueError: not enough values to unpack (expected 3, got 2)

If I try to bypass this by removing the ori_encoding eventually this fails:
        info_nce_loss = 0
        info_nce = InfoNCE(negative_mode='paired')
        # batch_size, num_negative, embedding_size = 1280, 5, 64
        # experts_num
        for i in range(6):
            query = ori_encoding[i]
            positive_key = ori_next_encoding[i]
            # [5, batch, emb_size]
            negative_keys = torch.cat((ori_encoding[0:i],ori_encoding[i+1:6]),0)
            # [5, batch, emb_size] -> [batch, 5, emb_size]
            negative_keys = torch.transpose(negative_keys,0,1)
            info_nce_loss += info_nce(query, positive_key, negative_keys)
            # pdb.set_trace()
        logger.log("train/info_nce_loss", info_nce_loss, step) 
        total_loss = critic_loss + 2500 * info_nce_loss
        
        In sac.py because ori_encoding doesn't exist.

**Comment by Lan131** [comment]
error occurs for soft_modu as well.

**Comment by Lan131** [comment]
All of the baselines except care and CMTA have this issue.

**Comment by niiceMing** [comment]
The latest commit has fixed this bug.

**Comment by yyds-xtt** [comment]
大佬 能发一份 能跑的代码吗 gaozhen610351@163.com

**Comment by yyds-xtt** [comment]
大佬 能发一份 能跑的代码吗 [gaozhen610351@163.com](mailto:gaozhen610351@163.com)

**Comment by yyds-xtt** [comment]
大佬 能发一份 能跑的代码吗 [gaozhen610351@163.com](mailto:gaozhen610351@163.com)
